# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Doctor Useful (Steve Hobdell)
email: hobdell.stephen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dr. Steve Hobdell is a ecommerce consultant since 2000 with an 
  interest in continually developing and understanding 
  coding and deployment as a collaborative team activity.
  He is currently very excited by Kubernetes and Docker.

  Steve is also an occasional (!) mountaineer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SteveHMountain
github_username: DoctorU

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
